/* Generated By:JavaCC: Do not edit this line. langXConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface langXConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BREAK = 12;
  /** RegularExpression Id. */
  int CLASS = 13;
  /** RegularExpression Id. */
  int CONSTRUCTOR = 14;
  /** RegularExpression Id. */
  int ELSE = 15;
  /** RegularExpression Id. */
  int EXTENDS = 16;
  /** RegularExpression Id. */
  int FOR = 17;
  /** RegularExpression Id. */
  int IF = 18;
  /** RegularExpression Id. */
  int INT = 19;
  /** RegularExpression Id. */
  int NEW = 20;
  /** RegularExpression Id. */
  int PRINT = 21;
  /** RegularExpression Id. */
  int READ = 22;
  /** RegularExpression Id. */
  int RETURN = 23;
  /** RegularExpression Id. */
  int STRING = 24;
  /** RegularExpression Id. */
  int SUPER = 25;
  /** RegularExpression Id. */
  int AND = 26;
  /** RegularExpression Id. */
  int OR = 27;
  /** RegularExpression Id. */
  int XOR = 28;
  /** RegularExpression Id. */
  int NOT = 29;
  /** RegularExpression Id. */
  int BYTE = 30;
  /** RegularExpression Id. */
  int SHORT = 31;
  /** RegularExpression Id. */
  int LONG = 32;
  /** RegularExpression Id. */
  int FLOAT = 33;
  /** RegularExpression Id. */
  int FINAL = 34;
  /** RegularExpression Id. */
  int PUBLIC = 35;
  /** RegularExpression Id. */
  int PRIVATE = 36;
  /** RegularExpression Id. */
  int PROTECTED = 37;
  /** RegularExpression Id. */
  int int_constant = 38;
  /** RegularExpression Id. */
  int string_constant = 39;
  /** RegularExpression Id. */
  int null_constant = 40;
  /** RegularExpression Id. */
  int float_constant = 41;
  /** RegularExpression Id. */
  int IDENT = 42;
  /** RegularExpression Id. */
  int LETTER = 43;
  /** RegularExpression Id. */
  int DIGIT = 44;
  /** RegularExpression Id. */
  int LPAREN = 45;
  /** RegularExpression Id. */
  int RPAREN = 46;
  /** RegularExpression Id. */
  int LBRACE = 47;
  /** RegularExpression Id. */
  int RBRACE = 48;
  /** RegularExpression Id. */
  int LBRACKET = 49;
  /** RegularExpression Id. */
  int RBRACKET = 50;
  /** RegularExpression Id. */
  int SEMICOLON = 51;
  /** RegularExpression Id. */
  int COMMA = 52;
  /** RegularExpression Id. */
  int DOT = 53;
  /** RegularExpression Id. */
  int ASSIGN = 54;
  /** RegularExpression Id. */
  int GT = 55;
  /** RegularExpression Id. */
  int LT = 56;
  /** RegularExpression Id. */
  int EQ = 57;
  /** RegularExpression Id. */
  int LE = 58;
  /** RegularExpression Id. */
  int GE = 59;
  /** RegularExpression Id. */
  int NEQ = 60;
  /** RegularExpression Id. */
  int PLUS = 61;
  /** RegularExpression Id. */
  int MINUS = 62;
  /** RegularExpression Id. */
  int STAR = 63;
  /** RegularExpression Id. */
  int SLASH = 64;
  /** RegularExpression Id. */
  int REM = 65;
  /** RegularExpression Id. */
  int INVALID_LEXICAL = 66;
  /** RegularExpression Id. */
  int INVALID_CONST = 67;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int multilinecomment = 1;
  /** Lexical state. */
  int singlelinecomment = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"/*\"",
    "\"//\"",
    "\"*/\"",
    "<token of kind 9>",
    "<token of kind 10>",
    "<token of kind 11>",
    "\"break\"",
    "\"class\"",
    "\"constructor\"",
    "\"else\"",
    "\"extends\"",
    "\"for\"",
    "\"if\"",
    "\"int\"",
    "\"new\"",
    "\"print\"",
    "\"read\"",
    "\"return\"",
    "\"string\"",
    "\"super\"",
    "\"&&\"",
    "\"||\"",
    "\"^\"",
    "\"!\"",
    "\"byte\"",
    "\"short\"",
    "\"long\"",
    "\"float\"",
    "\"final\"",
    "\"public\"",
    "\"private\"",
    "\"protected\"",
    "<int_constant>",
    "<string_constant>",
    "\"null\"",
    "<float_constant>",
    "<IDENT>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "<INVALID_LEXICAL>",
    "<INVALID_CONST>",
  };

}
